- name: Install Java
  dnf:
    pkg: 
    - java
    - net-tools
    state: present 
    update_cache: yes     

- name: create kafka group
  group:
    name: kafka
    state: present

- name: create kafka user
  user:
    name: kafka
    group: kafka

- name: check kafka directory
  stat:
    path: "{{kafka_workspace}}"
  register: directory_check

- name: Download and unpack kafka
  unarchive:
    src: "{{kafka_url}}"
    dest: "{{kafka_home}}"
    owner: kafka
    group: kafka
    creates: "{{kafka_workspace}}"
    mode: 0755
    remote_src: yes
  
- name: find kafka folder
  find: 
    paths: "{{kafka_home}}"
    pattern: "kafka_*"
    file_type: directory
  register: directory_name

- name: rename kafka folder
  shell: mv {{directory_name.files[0].path}} {{kafka_workspace}}
  when: not directory_check.stat.exists

- name: Set firewall rules
  shell: |
    firewall-cmd --zone=public --add-port=2888/udp --add-port=2888/tcp --permanent;
    firewall-cmd --zone=public --add-port=3888/udp --add-port=3888/tcp --permanent;
    firewall-cmd --zone=public --add-port=2181/udp --add-port=2181/tcp --permanent;
    firewall-cmd --zone=public --add-port=9092/udp --add-port=9092/tcp --permanent;
    firewall-cmd --zone=public --add-port=9093/udp --add-port=9093/tcp --permanent;
    firewall-cmd --reload
